[pytest]
addopts = --base-url https://www.saucedemo.com/ --headed  --tracing on
markers =
    only_browser: Run test only on specific browser
    unit: Fast unit tests (no browser)
    integration: Slow integration tests (real browser)